//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkoStosic_ZI.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHA2_CTX", Namespace="http://schemas.datacontract.org/2004/07/WCFZI")]
    [System.SerializableAttribute()]
    public partial struct SHA2_CTX : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<uint> bitlenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint datalenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<uint> stateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<uint> bitlen {
            get {
                return this.bitlenField;
            }
            set {
                if ((object.ReferenceEquals(this.bitlenField, value) != true)) {
                    this.bitlenField = value;
                    this.RaisePropertyChanged("bitlen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint datalen {
            get {
                return this.datalenField;
            }
            set {
                if ((this.datalenField.Equals(value) != true)) {
                    this.datalenField = value;
                    this.RaisePropertyChanged("datalen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<uint> state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.ISHA2")]
    public interface ISHA2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/DBL_INT_ADD", ReplyAction="http://tempuri.org/ISHA2/DBL_INT_ADDResponse")]
        DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDResponse DBL_INT_ADD(DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/DBL_INT_ADD", ReplyAction="http://tempuri.org/ISHA2/DBL_INT_ADDResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDResponse> DBL_INT_ADDAsync(DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/ROTLEFT", ReplyAction="http://tempuri.org/ISHA2/ROTLEFTResponse")]
        uint ROTLEFT(uint a, byte b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/ROTLEFT", ReplyAction="http://tempuri.org/ISHA2/ROTLEFTResponse")]
        System.Threading.Tasks.Task<uint> ROTLEFTAsync(uint a, byte b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/ROTRIGHT", ReplyAction="http://tempuri.org/ISHA2/ROTRIGHTResponse")]
        uint ROTRIGHT(uint a, byte b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/ROTRIGHT", ReplyAction="http://tempuri.org/ISHA2/ROTRIGHTResponse")]
        System.Threading.Tasks.Task<uint> ROTRIGHTAsync(uint a, byte b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/CH", ReplyAction="http://tempuri.org/ISHA2/CHResponse")]
        uint CH(uint x, uint y, uint z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/CH", ReplyAction="http://tempuri.org/ISHA2/CHResponse")]
        System.Threading.Tasks.Task<uint> CHAsync(uint x, uint y, uint z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/MAJ", ReplyAction="http://tempuri.org/ISHA2/MAJResponse")]
        uint MAJ(uint x, uint y, uint z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/MAJ", ReplyAction="http://tempuri.org/ISHA2/MAJResponse")]
        System.Threading.Tasks.Task<uint> MAJAsync(uint x, uint y, uint z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/EP0", ReplyAction="http://tempuri.org/ISHA2/EP0Response")]
        uint EP0(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/EP0", ReplyAction="http://tempuri.org/ISHA2/EP0Response")]
        System.Threading.Tasks.Task<uint> EP0Async(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/EP1", ReplyAction="http://tempuri.org/ISHA2/EP1Response")]
        uint EP1(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/EP1", ReplyAction="http://tempuri.org/ISHA2/EP1Response")]
        System.Threading.Tasks.Task<uint> EP1Async(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SIG0", ReplyAction="http://tempuri.org/ISHA2/SIG0Response")]
        uint SIG0(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SIG0", ReplyAction="http://tempuri.org/ISHA2/SIG0Response")]
        System.Threading.Tasks.Task<uint> SIG0Async(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SIG1", ReplyAction="http://tempuri.org/ISHA2/SIG1Response")]
        uint SIG1(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SIG1", ReplyAction="http://tempuri.org/ISHA2/SIG1Response")]
        System.Threading.Tasks.Task<uint> SIG1Async(uint x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Transform", ReplyAction="http://tempuri.org/ISHA2/SHA2TransformResponse")]
        DarkoStosic_ZI.ServiceReference4.SHA2TransformResponse SHA2Transform(DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Transform", ReplyAction="http://tempuri.org/ISHA2/SHA2TransformResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2TransformResponse> SHA2TransformAsync(DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Init", ReplyAction="http://tempuri.org/ISHA2/SHA2InitResponse")]
        DarkoStosic_ZI.ServiceReference4.SHA2InitResponse SHA2Init(DarkoStosic_ZI.ServiceReference4.SHA2InitRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Init", ReplyAction="http://tempuri.org/ISHA2/SHA2InitResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2InitResponse> SHA2InitAsync(DarkoStosic_ZI.ServiceReference4.SHA2InitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Update", ReplyAction="http://tempuri.org/ISHA2/SHA2UpdateResponse")]
        DarkoStosic_ZI.ServiceReference4.SHA2UpdateResponse SHA2Update(DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Update", ReplyAction="http://tempuri.org/ISHA2/SHA2UpdateResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2UpdateResponse> SHA2UpdateAsync(DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Final", ReplyAction="http://tempuri.org/ISHA2/SHA2FinalResponse")]
        DarkoStosic_ZI.ServiceReference4.SHA2FinalResponse SHA2Final(DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Final", ReplyAction="http://tempuri.org/ISHA2/SHA2FinalResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2FinalResponse> SHA2FinalAsync(DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Calculate", ReplyAction="http://tempuri.org/ISHA2/SHA2CalculateResponse")]
        string SHA2Calculate(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISHA2/SHA2Calculate", ReplyAction="http://tempuri.org/ISHA2/SHA2CalculateResponse")]
        System.Threading.Tasks.Task<string> SHA2CalculateAsync(string data);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DBL_INT_ADD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DBL_INT_ADDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public uint a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public uint b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public uint c;
        
        public DBL_INT_ADDRequest() {
        }
        
        public DBL_INT_ADDRequest(uint a, uint b, uint c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DBL_INT_ADDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DBL_INT_ADDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public uint a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public uint b;
        
        public DBL_INT_ADDResponse() {
        }
        
        public DBL_INT_ADDResponse(uint a, uint b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2Transform", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2TransformRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] data;
        
        public SHA2TransformRequest() {
        }
        
        public SHA2TransformRequest(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] data) {
            this.ctx = ctx;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2TransformResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2TransformResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        public SHA2TransformResponse() {
        }
        
        public SHA2TransformResponse(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            this.ctx = ctx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2Init", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2InitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        public SHA2InitRequest() {
        }
        
        public SHA2InitRequest(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            this.ctx = ctx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2InitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2InitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        public SHA2InitResponse() {
        }
        
        public SHA2InitResponse(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            this.ctx = ctx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public uint len;
        
        public SHA2UpdateRequest() {
        }
        
        public SHA2UpdateRequest(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] data, uint len) {
            this.ctx = ctx;
            this.data = data;
            this.len = len;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        public SHA2UpdateResponse() {
        }
        
        public SHA2UpdateResponse(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            this.ctx = ctx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2Final", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2FinalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] hash;
        
        public SHA2FinalRequest() {
        }
        
        public SHA2FinalRequest(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] hash) {
            this.ctx = ctx;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SHA2FinalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SHA2FinalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx;
        
        public SHA2FinalResponse() {
        }
        
        public SHA2FinalResponse(DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            this.ctx = ctx;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISHA2Channel : DarkoStosic_ZI.ServiceReference4.ISHA2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SHA2Client : System.ServiceModel.ClientBase<DarkoStosic_ZI.ServiceReference4.ISHA2>, DarkoStosic_ZI.ServiceReference4.ISHA2 {
        
        public SHA2Client() {
        }
        
        public SHA2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SHA2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SHA2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SHA2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDResponse DarkoStosic_ZI.ServiceReference4.ISHA2.DBL_INT_ADD(DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest request) {
            return base.Channel.DBL_INT_ADD(request);
        }
        
        public void DBL_INT_ADD(ref uint a, ref uint b, uint c) {
            DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest inValue = new DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDResponse retVal = ((DarkoStosic_ZI.ServiceReference4.ISHA2)(this)).DBL_INT_ADD(inValue);
            a = retVal.a;
            b = retVal.b;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDResponse> DBL_INT_ADDAsync(DarkoStosic_ZI.ServiceReference4.DBL_INT_ADDRequest request) {
            return base.Channel.DBL_INT_ADDAsync(request);
        }
        
        public uint ROTLEFT(uint a, byte b) {
            return base.Channel.ROTLEFT(a, b);
        }
        
        public System.Threading.Tasks.Task<uint> ROTLEFTAsync(uint a, byte b) {
            return base.Channel.ROTLEFTAsync(a, b);
        }
        
        public uint ROTRIGHT(uint a, byte b) {
            return base.Channel.ROTRIGHT(a, b);
        }
        
        public System.Threading.Tasks.Task<uint> ROTRIGHTAsync(uint a, byte b) {
            return base.Channel.ROTRIGHTAsync(a, b);
        }
        
        public uint CH(uint x, uint y, uint z) {
            return base.Channel.CH(x, y, z);
        }
        
        public System.Threading.Tasks.Task<uint> CHAsync(uint x, uint y, uint z) {
            return base.Channel.CHAsync(x, y, z);
        }
        
        public uint MAJ(uint x, uint y, uint z) {
            return base.Channel.MAJ(x, y, z);
        }
        
        public System.Threading.Tasks.Task<uint> MAJAsync(uint x, uint y, uint z) {
            return base.Channel.MAJAsync(x, y, z);
        }
        
        public uint EP0(uint x) {
            return base.Channel.EP0(x);
        }
        
        public System.Threading.Tasks.Task<uint> EP0Async(uint x) {
            return base.Channel.EP0Async(x);
        }
        
        public uint EP1(uint x) {
            return base.Channel.EP1(x);
        }
        
        public System.Threading.Tasks.Task<uint> EP1Async(uint x) {
            return base.Channel.EP1Async(x);
        }
        
        public uint SIG0(uint x) {
            return base.Channel.SIG0(x);
        }
        
        public System.Threading.Tasks.Task<uint> SIG0Async(uint x) {
            return base.Channel.SIG0Async(x);
        }
        
        public uint SIG1(uint x) {
            return base.Channel.SIG1(x);
        }
        
        public System.Threading.Tasks.Task<uint> SIG1Async(uint x) {
            return base.Channel.SIG1Async(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference4.SHA2TransformResponse DarkoStosic_ZI.ServiceReference4.ISHA2.SHA2Transform(DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest request) {
            return base.Channel.SHA2Transform(request);
        }
        
        public void SHA2Transform(ref DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] data) {
            DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest inValue = new DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest();
            inValue.ctx = ctx;
            inValue.data = data;
            DarkoStosic_ZI.ServiceReference4.SHA2TransformResponse retVal = ((DarkoStosic_ZI.ServiceReference4.ISHA2)(this)).SHA2Transform(inValue);
            ctx = retVal.ctx;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2TransformResponse> SHA2TransformAsync(DarkoStosic_ZI.ServiceReference4.SHA2TransformRequest request) {
            return base.Channel.SHA2TransformAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference4.SHA2InitResponse DarkoStosic_ZI.ServiceReference4.ISHA2.SHA2Init(DarkoStosic_ZI.ServiceReference4.SHA2InitRequest request) {
            return base.Channel.SHA2Init(request);
        }
        
        public void SHA2Init(ref DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx) {
            DarkoStosic_ZI.ServiceReference4.SHA2InitRequest inValue = new DarkoStosic_ZI.ServiceReference4.SHA2InitRequest();
            inValue.ctx = ctx;
            DarkoStosic_ZI.ServiceReference4.SHA2InitResponse retVal = ((DarkoStosic_ZI.ServiceReference4.ISHA2)(this)).SHA2Init(inValue);
            ctx = retVal.ctx;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2InitResponse> SHA2InitAsync(DarkoStosic_ZI.ServiceReference4.SHA2InitRequest request) {
            return base.Channel.SHA2InitAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference4.SHA2UpdateResponse DarkoStosic_ZI.ServiceReference4.ISHA2.SHA2Update(DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest request) {
            return base.Channel.SHA2Update(request);
        }
        
        public void SHA2Update(ref DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] data, uint len) {
            DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest inValue = new DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest();
            inValue.ctx = ctx;
            inValue.data = data;
            inValue.len = len;
            DarkoStosic_ZI.ServiceReference4.SHA2UpdateResponse retVal = ((DarkoStosic_ZI.ServiceReference4.ISHA2)(this)).SHA2Update(inValue);
            ctx = retVal.ctx;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2UpdateResponse> SHA2UpdateAsync(DarkoStosic_ZI.ServiceReference4.SHA2UpdateRequest request) {
            return base.Channel.SHA2UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference4.SHA2FinalResponse DarkoStosic_ZI.ServiceReference4.ISHA2.SHA2Final(DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest request) {
            return base.Channel.SHA2Final(request);
        }
        
        public void SHA2Final(ref DarkoStosic_ZI.ServiceReference4.SHA2_CTX ctx, byte[] hash) {
            DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest inValue = new DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest();
            inValue.ctx = ctx;
            inValue.hash = hash;
            DarkoStosic_ZI.ServiceReference4.SHA2FinalResponse retVal = ((DarkoStosic_ZI.ServiceReference4.ISHA2)(this)).SHA2Final(inValue);
            ctx = retVal.ctx;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference4.SHA2FinalResponse> SHA2FinalAsync(DarkoStosic_ZI.ServiceReference4.SHA2FinalRequest request) {
            return base.Channel.SHA2FinalAsync(request);
        }
        
        public string SHA2Calculate(string data) {
            return base.Channel.SHA2Calculate(data);
        }
        
        public System.Threading.Tasks.Task<string> SHA2CalculateAsync(string data) {
            return base.Channel.SHA2CalculateAsync(data);
        }
    }
}
