//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkoStosic_ZI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPlayfairCipher")]
    public interface IPlayfairCipher {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Mod", ReplyAction="http://tempuri.org/IPlayfairCipher/ModResponse")]
        int Mod(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Mod", ReplyAction="http://tempuri.org/IPlayfairCipher/ModResponse")]
        System.Threading.Tasks.Task<int> ModAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/FindAllOccurrences", ReplyAction="http://tempuri.org/IPlayfairCipher/FindAllOccurrencesResponse")]
        System.Collections.Generic.List<int> FindAllOccurrences(string str, char value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/FindAllOccurrences", ReplyAction="http://tempuri.org/IPlayfairCipher/FindAllOccurrencesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> FindAllOccurrencesAsync(string str, char value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/RemoveAllDuplicates", ReplyAction="http://tempuri.org/IPlayfairCipher/RemoveAllDuplicatesResponse")]
        string RemoveAllDuplicates(string str, System.Collections.Generic.List<int> indexes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/RemoveAllDuplicates", ReplyAction="http://tempuri.org/IPlayfairCipher/RemoveAllDuplicatesResponse")]
        System.Threading.Tasks.Task<string> RemoveAllDuplicatesAsync(string str, System.Collections.Generic.List<int> indexes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/GenerateKeySquare", ReplyAction="http://tempuri.org/IPlayfairCipher/GenerateKeySquareResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<char>> GenerateKeySquare(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/GenerateKeySquare", ReplyAction="http://tempuri.org/IPlayfairCipher/GenerateKeySquareResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<char>>> GenerateKeySquareAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/GetPosition", ReplyAction="http://tempuri.org/IPlayfairCipher/GetPositionResponse")]
        DarkoStosic_ZI.ServiceReference1.GetPositionResponse GetPosition(DarkoStosic_ZI.ServiceReference1.GetPositionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/GetPosition", ReplyAction="http://tempuri.org/IPlayfairCipher/GetPositionResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.GetPositionResponse> GetPositionAsync(DarkoStosic_ZI.ServiceReference1.GetPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameRow", ReplyAction="http://tempuri.org/IPlayfairCipher/SameRowResponse")]
        DarkoStosic_ZI.ServiceReference1.SameRowResponse SameRow(DarkoStosic_ZI.ServiceReference1.SameRowRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameRow", ReplyAction="http://tempuri.org/IPlayfairCipher/SameRowResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameRowResponse> SameRowAsync(DarkoStosic_ZI.ServiceReference1.SameRowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/SameColumnResponse")]
        DarkoStosic_ZI.ServiceReference1.SameColumnResponse SameColumn(DarkoStosic_ZI.ServiceReference1.SameColumnRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/SameColumnResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameColumnResponse> SameColumnAsync(DarkoStosic_ZI.ServiceReference1.SameColumnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameRowColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/SameRowColumnResponse")]
        DarkoStosic_ZI.ServiceReference1.SameRowColumnResponse SameRowColumn(DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/SameRowColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/SameRowColumnResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameRowColumnResponse> SameRowColumnAsync(DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/DifferentRowColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/DifferentRowColumnResponse")]
        DarkoStosic_ZI.ServiceReference1.DifferentRowColumnResponse DifferentRowColumn(DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/DifferentRowColumn", ReplyAction="http://tempuri.org/IPlayfairCipher/DifferentRowColumnResponse")]
        System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.DifferentRowColumnResponse> DifferentRowColumnAsync(DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/RemoveOtherChars", ReplyAction="http://tempuri.org/IPlayfairCipher/RemoveOtherCharsResponse")]
        string RemoveOtherChars(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/RemoveOtherChars", ReplyAction="http://tempuri.org/IPlayfairCipher/RemoveOtherCharsResponse")]
        System.Threading.Tasks.Task<string> RemoveOtherCharsAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/AdjustOutput", ReplyAction="http://tempuri.org/IPlayfairCipher/AdjustOutputResponse")]
        string AdjustOutput(string input, string output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/AdjustOutput", ReplyAction="http://tempuri.org/IPlayfairCipher/AdjustOutputResponse")]
        System.Threading.Tasks.Task<string> AdjustOutputAsync(string input, string output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Cipher", ReplyAction="http://tempuri.org/IPlayfairCipher/CipherResponse")]
        string Cipher(string input, string key, bool encipher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Cipher", ReplyAction="http://tempuri.org/IPlayfairCipher/CipherResponse")]
        System.Threading.Tasks.Task<string> CipherAsync(string input, string key, bool encipher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Encipher", ReplyAction="http://tempuri.org/IPlayfairCipher/EncipherResponse")]
        string Encipher(string input, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Encipher", ReplyAction="http://tempuri.org/IPlayfairCipher/EncipherResponse")]
        System.Threading.Tasks.Task<string> EncipherAsync(string input, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Decipher", ReplyAction="http://tempuri.org/IPlayfairCipher/DecipherResponse")]
        string Decipher(string input, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayfairCipher/Decipher", ReplyAction="http://tempuri.org/IPlayfairCipher/DecipherResponse")]
        System.Threading.Tasks.Task<string> DecipherAsync(string input, string key);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPosition", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public char ch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int row;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int col;
        
        public GetPositionRequest() {
        }
        
        public GetPositionRequest(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, char ch, int row, int col) {
            this.keySquare = keySquare;
            this.ch = ch;
            this.row = row;
            this.col = col;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPositionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int row;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int col;
        
        public GetPositionResponse() {
        }
        
        public GetPositionResponse(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row, int col) {
            this.keySquare = keySquare;
            this.row = row;
            this.col = col;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameRow", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameRowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int row;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int col1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int col2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int encipher;
        
        public SameRowRequest() {
        }
        
        public SameRowRequest(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row, int col1, int col2, int encipher) {
            this.keySquare = keySquare;
            this.row = row;
            this.col1 = col1;
            this.col2 = col2;
            this.encipher = encipher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameRowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameRowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<char> SameRowResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        public SameRowResponse() {
        }
        
        public SameRowResponse(System.Collections.Generic.List<char> SameRowResult, System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare) {
            this.SameRowResult = SameRowResult;
            this.keySquare = keySquare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameColumn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameColumnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int col;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int row1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int row2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int encipher;
        
        public SameColumnRequest() {
        }
        
        public SameColumnRequest(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int col, int row1, int row2, int encipher) {
            this.keySquare = keySquare;
            this.col = col;
            this.row1 = row1;
            this.row2 = row2;
            this.encipher = encipher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameColumnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameColumnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<char> SameColumnResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        public SameColumnResponse() {
        }
        
        public SameColumnResponse(System.Collections.Generic.List<char> SameColumnResult, System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare) {
            this.SameColumnResult = SameColumnResult;
            this.keySquare = keySquare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameRowColumn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameRowColumnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int row;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int col;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int encipher;
        
        public SameRowColumnRequest() {
        }
        
        public SameRowColumnRequest(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row, int col, int encipher) {
            this.keySquare = keySquare;
            this.row = row;
            this.col = col;
            this.encipher = encipher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SameRowColumnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SameRowColumnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<char> SameRowColumnResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        public SameRowColumnResponse() {
        }
        
        public SameRowColumnResponse(System.Collections.Generic.List<char> SameRowColumnResult, System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare) {
            this.SameRowColumnResult = SameRowColumnResult;
            this.keySquare = keySquare;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DifferentRowColumn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DifferentRowColumnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int row1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int col1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int row2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int col2;
        
        public DifferentRowColumnRequest() {
        }
        
        public DifferentRowColumnRequest(System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row1, int col1, int row2, int col2) {
            this.keySquare = keySquare;
            this.row1 = row1;
            this.col1 = col1;
            this.row2 = row2;
            this.col2 = col2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DifferentRowColumnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DifferentRowColumnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<char> DifferentRowColumnResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare;
        
        public DifferentRowColumnResponse() {
        }
        
        public DifferentRowColumnResponse(System.Collections.Generic.List<char> DifferentRowColumnResult, System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare) {
            this.DifferentRowColumnResult = DifferentRowColumnResult;
            this.keySquare = keySquare;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayfairCipherChannel : DarkoStosic_ZI.ServiceReference1.IPlayfairCipher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayfairCipherClient : System.ServiceModel.ClientBase<DarkoStosic_ZI.ServiceReference1.IPlayfairCipher>, DarkoStosic_ZI.ServiceReference1.IPlayfairCipher {
        
        public PlayfairCipherClient() {
        }
        
        public PlayfairCipherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayfairCipherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayfairCipherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayfairCipherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Mod(int a, int b) {
            return base.Channel.Mod(a, b);
        }
        
        public System.Threading.Tasks.Task<int> ModAsync(int a, int b) {
            return base.Channel.ModAsync(a, b);
        }
        
        public System.Collections.Generic.List<int> FindAllOccurrences(string str, char value) {
            return base.Channel.FindAllOccurrences(str, value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> FindAllOccurrencesAsync(string str, char value) {
            return base.Channel.FindAllOccurrencesAsync(str, value);
        }
        
        public string RemoveAllDuplicates(string str, System.Collections.Generic.List<int> indexes) {
            return base.Channel.RemoveAllDuplicates(str, indexes);
        }
        
        public System.Threading.Tasks.Task<string> RemoveAllDuplicatesAsync(string str, System.Collections.Generic.List<int> indexes) {
            return base.Channel.RemoveAllDuplicatesAsync(str, indexes);
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<char>> GenerateKeySquare(string key) {
            return base.Channel.GenerateKeySquare(key);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<char>>> GenerateKeySquareAsync(string key) {
            return base.Channel.GenerateKeySquareAsync(key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference1.GetPositionResponse DarkoStosic_ZI.ServiceReference1.IPlayfairCipher.GetPosition(DarkoStosic_ZI.ServiceReference1.GetPositionRequest request) {
            return base.Channel.GetPosition(request);
        }
        
        public void GetPosition(ref System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, char ch, ref int row, ref int col) {
            DarkoStosic_ZI.ServiceReference1.GetPositionRequest inValue = new DarkoStosic_ZI.ServiceReference1.GetPositionRequest();
            inValue.keySquare = keySquare;
            inValue.ch = ch;
            inValue.row = row;
            inValue.col = col;
            DarkoStosic_ZI.ServiceReference1.GetPositionResponse retVal = ((DarkoStosic_ZI.ServiceReference1.IPlayfairCipher)(this)).GetPosition(inValue);
            keySquare = retVal.keySquare;
            row = retVal.row;
            col = retVal.col;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.GetPositionResponse> GetPositionAsync(DarkoStosic_ZI.ServiceReference1.GetPositionRequest request) {
            return base.Channel.GetPositionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference1.SameRowResponse DarkoStosic_ZI.ServiceReference1.IPlayfairCipher.SameRow(DarkoStosic_ZI.ServiceReference1.SameRowRequest request) {
            return base.Channel.SameRow(request);
        }
        
        public System.Collections.Generic.List<char> SameRow(ref System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row, int col1, int col2, int encipher) {
            DarkoStosic_ZI.ServiceReference1.SameRowRequest inValue = new DarkoStosic_ZI.ServiceReference1.SameRowRequest();
            inValue.keySquare = keySquare;
            inValue.row = row;
            inValue.col1 = col1;
            inValue.col2 = col2;
            inValue.encipher = encipher;
            DarkoStosic_ZI.ServiceReference1.SameRowResponse retVal = ((DarkoStosic_ZI.ServiceReference1.IPlayfairCipher)(this)).SameRow(inValue);
            keySquare = retVal.keySquare;
            return retVal.SameRowResult;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameRowResponse> SameRowAsync(DarkoStosic_ZI.ServiceReference1.SameRowRequest request) {
            return base.Channel.SameRowAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference1.SameColumnResponse DarkoStosic_ZI.ServiceReference1.IPlayfairCipher.SameColumn(DarkoStosic_ZI.ServiceReference1.SameColumnRequest request) {
            return base.Channel.SameColumn(request);
        }
        
        public System.Collections.Generic.List<char> SameColumn(ref System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int col, int row1, int row2, int encipher) {
            DarkoStosic_ZI.ServiceReference1.SameColumnRequest inValue = new DarkoStosic_ZI.ServiceReference1.SameColumnRequest();
            inValue.keySquare = keySquare;
            inValue.col = col;
            inValue.row1 = row1;
            inValue.row2 = row2;
            inValue.encipher = encipher;
            DarkoStosic_ZI.ServiceReference1.SameColumnResponse retVal = ((DarkoStosic_ZI.ServiceReference1.IPlayfairCipher)(this)).SameColumn(inValue);
            keySquare = retVal.keySquare;
            return retVal.SameColumnResult;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameColumnResponse> SameColumnAsync(DarkoStosic_ZI.ServiceReference1.SameColumnRequest request) {
            return base.Channel.SameColumnAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference1.SameRowColumnResponse DarkoStosic_ZI.ServiceReference1.IPlayfairCipher.SameRowColumn(DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest request) {
            return base.Channel.SameRowColumn(request);
        }
        
        public System.Collections.Generic.List<char> SameRowColumn(ref System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row, int col, int encipher) {
            DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest inValue = new DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest();
            inValue.keySquare = keySquare;
            inValue.row = row;
            inValue.col = col;
            inValue.encipher = encipher;
            DarkoStosic_ZI.ServiceReference1.SameRowColumnResponse retVal = ((DarkoStosic_ZI.ServiceReference1.IPlayfairCipher)(this)).SameRowColumn(inValue);
            keySquare = retVal.keySquare;
            return retVal.SameRowColumnResult;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.SameRowColumnResponse> SameRowColumnAsync(DarkoStosic_ZI.ServiceReference1.SameRowColumnRequest request) {
            return base.Channel.SameRowColumnAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DarkoStosic_ZI.ServiceReference1.DifferentRowColumnResponse DarkoStosic_ZI.ServiceReference1.IPlayfairCipher.DifferentRowColumn(DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest request) {
            return base.Channel.DifferentRowColumn(request);
        }
        
        public System.Collections.Generic.List<char> DifferentRowColumn(ref System.Collections.Generic.List<System.Collections.Generic.List<char>> keySquare, int row1, int col1, int row2, int col2) {
            DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest inValue = new DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest();
            inValue.keySquare = keySquare;
            inValue.row1 = row1;
            inValue.col1 = col1;
            inValue.row2 = row2;
            inValue.col2 = col2;
            DarkoStosic_ZI.ServiceReference1.DifferentRowColumnResponse retVal = ((DarkoStosic_ZI.ServiceReference1.IPlayfairCipher)(this)).DifferentRowColumn(inValue);
            keySquare = retVal.keySquare;
            return retVal.DifferentRowColumnResult;
        }
        
        public System.Threading.Tasks.Task<DarkoStosic_ZI.ServiceReference1.DifferentRowColumnResponse> DifferentRowColumnAsync(DarkoStosic_ZI.ServiceReference1.DifferentRowColumnRequest request) {
            return base.Channel.DifferentRowColumnAsync(request);
        }
        
        public string RemoveOtherChars(string input) {
            return base.Channel.RemoveOtherChars(input);
        }
        
        public System.Threading.Tasks.Task<string> RemoveOtherCharsAsync(string input) {
            return base.Channel.RemoveOtherCharsAsync(input);
        }
        
        public string AdjustOutput(string input, string output) {
            return base.Channel.AdjustOutput(input, output);
        }
        
        public System.Threading.Tasks.Task<string> AdjustOutputAsync(string input, string output) {
            return base.Channel.AdjustOutputAsync(input, output);
        }
        
        public string Cipher(string input, string key, bool encipher) {
            return base.Channel.Cipher(input, key, encipher);
        }
        
        public System.Threading.Tasks.Task<string> CipherAsync(string input, string key, bool encipher) {
            return base.Channel.CipherAsync(input, key, encipher);
        }
        
        public string Encipher(string input, string key) {
            return base.Channel.Encipher(input, key);
        }
        
        public System.Threading.Tasks.Task<string> EncipherAsync(string input, string key) {
            return base.Channel.EncipherAsync(input, key);
        }
        
        public string Decipher(string input, string key) {
            return base.Channel.Decipher(input, key);
        }
        
        public System.Threading.Tasks.Task<string> DecipherAsync(string input, string key) {
            return base.Channel.DecipherAsync(input, key);
        }
    }
}
